development:
  adapter: postgres
  host: host.docker.internal # puede que haya que cambiar los hosts por localhost aca, yo porque trabajo con WSL
  database: fudo_development
  user: postgres
  password: postgres
  port: 5432

test:
  adapter: postgres
  host: host.docker.internal
  database: fudo_test
  user: postgres
  password: postgres

production:
  adapter: postgres
  host: host.docker.internal
  database: fudo_production
  user: postgres
  password: postgres
  port: 5432